dataset:
  augmentation:
    brightness: 0.3
    contrast: 0.3
    hue: 0.1
    p_flip: 0.5
    rotation_range:
    - -15
    - 15
    saturation: 0.3
    scale_range:
    - 0.7
    - 1.3
  batch_size: 2
  img_size:
  - 240
  - 320
  num_workers: 4
  sequence_length: 3
  sequence_stride: 2
evaluation:
  enabled: true
  metrics:
  - iou
  - f1
  - precision
  - recall
losses:
  boundary_weight: 1.0
  ce_weight: 0.5
  dice_weight: 1.5
  temporal_weight: 0.5
model:
  d_conv: 4
  d_state: 16
  dropout: 0.2
  expand: 2
  hidden_dims:
  - 32
  - 64
  - 128
  input_dim: 3
  temporal_window: 3
optimizer:
  betas:
  - 0.9
  - 0.95
  lr: 5.0e-05
  type: AdamW
  weight_decay: 0.01
paths:
  checkpoints: checkpoints/mamba_binary
  davis_root: /mnt/c/Datasets/DAVIS
  logs: logs/mamba_binary
  visualizations: visualizations/mamba_binary
scheduler:
  min_lr: 1e-6
  type: onecycle
training:
  epochs: 100
  grad_clip_value: 0.5
  gradient_accumulation_steps: 2
  mixed_precision: true
  patience: 15
  save_every: 5
  validate_every: 1
visualization:
  dir: visualizations/mamba_binary
  enabled: true
  interval: 5
